"""multi-context, sharing, accounts

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-12

Additive only. Hand-adjusted from the autogenerated draft so it is safe against
a live database with existing rows:

* new NOT NULL columns carry a server_default (otherwise the ALTER fails on a
  populated table);
* project slugs are backfilled from existing names *before* the unique
  constraint is applied;
* an existing single-context deployment gets a default context binding, so
  already-connected clients keep working untouched;
* constraint changes run through batch_alter_table for SQLite (CI) as well as
  Postgres (production).
"""
import re

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def _slugify(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")
    return slug[:100] or "context"


def upgrade() -> None:
    # --- new tables ---------------------------------------------------------
    op.create_table(
        "rate_events",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("key", "window_start"),
    )
    op.create_table(
        "email_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('verify','reset')", name="ck_email_token_kind"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index("ix_email_tokens_user", "email_tokens", ["user_id"], unique=False)

    op.create_table(
        "context_bindings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("agent_connection_id", sa.String(length=36), nullable=True),
        sa.Column("client_session_ref", sa.String(length=128), nullable=True),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "agent_connection_id",
            "client_session_ref",
            name="uq_context_binding",
        ),
    )
    op.create_index("ix_bindings_user", "context_bindings", ["user_id"], unique=False)

    op.create_table(
        "invites",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=False),
        sa.Column("used_count", sa.Integer(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role IN ('owner','admin','member','viewer')", name="ck_invite_role"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code_hash"),
    )
    op.create_index("ix_invites_email", "invites", ["email"], unique=False)
    op.create_index("ix_invites_project", "invites", ["project_id"], unique=False)

    # --- users: account lifecycle ------------------------------------------
    op.add_column(
        "users", sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "users", sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "failed_login_count", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "users", sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True)
    )
    # Accounts that predate public signup were provisioned by an operator, so
    # treat them as already verified rather than locking them out.
    op.execute(
        "UPDATE users SET email_verified_at = created_at WHERE email_verified_at IS NULL"
    )

    # --- projects: slug + archive ------------------------------------------
    op.add_column("projects", sa.Column("slug", sa.String(length=120), nullable=True))
    op.add_column(
        "projects", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True)
    )

    # Backfill slugs from names before the unique constraint lands.
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, name FROM projects")).fetchall()
    taken: set[str] = set()
    for row in rows:
        base = _slugify(row[1])
        candidate, n = base, 1
        while candidate in taken:
            n += 1
            candidate = f"{base}-{n}"
        taken.add(candidate)
        conn.execute(
            sa.text("UPDATE projects SET slug = :slug WHERE id = :id"),
            {"slug": candidate, "id": row[0]},
        )

    with op.batch_alter_table("projects") as batch:
        batch.create_unique_constraint("uq_projects_slug", ["slug"])

    # --- backfill bindings for an existing single-context deployment --------
    # If a user has exactly one membership, pin each of their live connections
    # to it so nothing has to be re-selected after the upgrade.
    bindings = conn.execute(
        sa.text(
            """
            SELECT ac.user_id, ac.id AS conn_id, m.project_id
            FROM agent_connections ac
            JOIN memberships m ON m.user_id = ac.user_id
            WHERE ac.revoked_at IS NULL
              AND (SELECT COUNT(*) FROM memberships m2 WHERE m2.user_id = ac.user_id) = 1
            """
        )
    ).fetchall()
    for user_id, conn_id, project_id in bindings:
        conn.execute(
            sa.text(
                "INSERT INTO context_bindings "
                "(id, user_id, agent_connection_id, client_session_ref, project_id, updated_at) "
                "VALUES (:id, :user_id, :conn_id, NULL, :project_id, CURRENT_TIMESTAMP)"
            ),
            {
                "id": f"{user_id[:8]}-{conn_id[:8]}-backfill-0000-000000000000"[:36],
                "user_id": user_id,
                "conn_id": conn_id,
                "project_id": project_id,
            },
        )


def downgrade() -> None:
    with op.batch_alter_table("projects") as batch:
        batch.drop_constraint("uq_projects_slug", type_="unique")
    op.drop_column("projects", "archived_at")
    op.drop_column("projects", "slug")
    op.drop_column("users", "locked_until")
    op.drop_column("users", "failed_login_count")
    op.drop_column("users", "last_login_at")
    op.drop_column("users", "email_verified_at")
    op.drop_index("ix_invites_project", table_name="invites")
    op.drop_index("ix_invites_email", table_name="invites")
    op.drop_table("invites")
    op.drop_index("ix_bindings_user", table_name="context_bindings")
    op.drop_table("context_bindings")
    op.drop_index("ix_email_tokens_user", table_name="email_tokens")
    op.drop_table("email_tokens")
    op.drop_table("rate_events")
